obj-$(CONFIG_ESWIN_DEV_DMA_BUF) += es_dev_buf.o

ES_DEV_DMA_BUF_HEADER := $(srctree)/drivers/memory/eswin/es_dev_buf/include/linux
COPY_HEADERS:=$(shell mkdir -p include/linux && cp $(ES_DEV_DMA_BUF_HEADER)/*.h include/linux)

